site_name: W.S.S-Wiki
site_url: https://wiki.51320721.xyz
repo_url: https://github.com/CHINAGJOGE/W.S.S-Wiki

theme:
  name: material
  logo: theme:
  name: material
  logo: /assets/logo1.png
  language: zh
  palette:
    # 自动切换深色/浅色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top # 回到顶部按钮
    - search.suggest
    - search.highlight
    - content.code.copy # 代码块一键复制

markdown_extensions:
  - admonition # 提示块
  - pymdownx.details # 可折叠的提示块
  - pymdownx.superfences # 嵌套代码块
  - pymdownx.tabbed:
      alternate_style: true # 现代选项卡
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - with-pdf
