site_name: W.S.S-Wiki
site_url: https://wiki.51320721.xyz
repo_url: https://github.com/CHINAGUOGE/W.S.S-Wiki

theme:
  name: material
  logo: /assets/logo1.png
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换至深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换至浅色模式
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition          # 提示块
  - pymdownx.details    # 可折叠提示块
  - pymdownx.superfences # 嵌套代码块
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite # 支持内联代码样式
  - pymdownx.snippets
  - attr_list           # 用于实现黑幕 [文字]{.heimu}
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
#  - with-pdf